apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: precedents-pruning
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: main
              env:
              - name: PRECEDENTS_URI
                valueFrom:
                  configMapKeyRef:
                    key: precedentsUri
                    name: precedents-configs
              - $patch: delete
                name: PRUNE_URL  
              - name: PRUNE_URL
                value: $(PRECEDENTS_URI)/v1/graph/prune
              - $patch: delete
                name: EDGE_AUTH_URI          
              - name: TOKEN_AUTH_URI
                valueFrom:
                  configMapKeyRef:
                    key: tokenAuthUri
                    name: precedents-configs
              - name: EDGE_AUTH_URI
                value: $(TOKEN_AUTH_URI)
              - $patch: delete
                name: KEY_IDENTIFIER
              - name: TOKEN_AUTH_PRIVATE_KEY_ID
                valueFrom:
                  secretKeyRef:
                    key: tokenAuthPrivateKeyId
                    name: precedents-secrets
              - name: KEY_IDENTIFIER
                value: $(TOKEN_AUTH_PRIVATE_KEY_ID)
              - $patch: delete
                name: SELF_SIGNING_PRIVATE_KEY
              - name: TOKEN_AUTH_PRIVATE_KEY
                valueFrom:
                  secretKeyRef:
                    key: tokenAuthPrivateKey
                    name: precedents-secrets
              - name: SELF_SIGNING_PRIVATE_KEY
                value: $(TOKEN_AUTH_PRIVATE_KEY)




