# This file is not referenced in kustomization.yaml 
# k-api use this file to create new patch file for release name
# and then add that file in the kustomization.yaml file
apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: release
enabled: true
patches:
- target:
    name: release
    kind: LabelTransformer
  patch: |-
    apiVersion: builtin
    kind: LabelTransformer
    metadata:
      name: release
    labels:
      release: whatever