FROM quay.io/deis/lightweight-docker-go:v0.2.0
FROM debian:stretch as base

# This is a template Dockerfile for the bundle's invocation image
# You can customize it to use different base images, install tools and copy configuration files.
#
# Porter will use it as a template and append lines to it for the mixins
# and to set the CMD appropriately for the CNAB specification.
#
# Add the following line to porter.yaml to instruct Porter to use this template
# dockerfile: Dockerfile.tmpl

# You can control where the mixin's Dockerfile lines are inserted into this file by moving "# PORTER_MIXINS" line
# another location in this file. If you remove that line, the mixins generated content is appended to this file.
# PORTER_MIXINS

ARG HELM_VERSION=v2.16.0
RUN apt-get update && \
 apt-get install -y curl && \
 curl -o helm.tgz https://get.helm.sh/helm-$HELM_VERSION-linux-amd64.tar.gz && \
 tar -xzf helm.tgz && \
 mv linux-amd64/helm /usr/local/bin && \
 rm helm.tgz

RUN helm init --client-only

RUN helm repo add qlik-edge https://qlik.bintray.com/edge

RUN mkdir -p /tmp/.chartcache
ARG QLIKSENSE_INIT_VERSION=1.1.0
RUN helm fetch qlik-edge/qliksense-init --version $QLIKSENSE_INIT_VERSION --untar -d /tmp/.chartcache/

# CI job will update this version and make a PR
ARG QSEOK_VERSION=1.12.89 

# The Qlik docker registry to use for Image layers
ARG QLIK_REGISTRY=qlik-docker-qsefe.bintray.io

# Air Gapped operation, images are copied to invocation image (this one)
# to enable images to be pushed to private docker registry
ARG AIR_GAPPED=true

COPY --from=0 /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
# Use the BUNDLE_DIR build argument to copy files into the bundle
ARG BUNDLE_DIR
COPY . $BUNDLE_DIR
