- op: replace
  path: /spec/podSpec/containers/0/imagePullPolicy
  value: IfNotPresent
- op: replace
  path: /spec/podSpec/volumes/1/secret
  value:
    secretName: engine-secrets
    items:
      - key: tokenAuthPrivateKey
        path: jwtPrivateKey
- op: replace
  path: /spec/podSpec/containers/0/args
  value:
  - -S
  - AcceptEULA=$(ACCEPT_EULA)
  - -S
  - DocumentDirectory=/qlik/apps
  - -S
  - EnableRestartOnSessionStall=1
  - -S
  - PrometheusServicePort=9090
  - -S
  - DesktopPort=9076
  - -S
  - EnableNumericalAbbreviation=0
  - -S
  - HttpTrafficLogVerbosity=4
  - -S
  - TrafficLogVerbosity=0
  - -S
  - SystemLogVerbosity=4
  - -S
  - AuditLogVerbosity=0
  - -S
  - PerformanceLogVerbosity=0
  - -S
  - QixPerformanceLogVerbosity=0
  - -S
  - SessionLogVerbosity=4
  - -S
  - ScriptLogVerbosity=4
  - -S
  - SmartSearchQueryLogVerbosity=3
  - -S
  - SmartSearchIndexLogVerbosity=3
  - -S
  - SSEVerbosity=4
  - -S
  - EventBusLogVerbosity=4
  - -S
  - EnableExtServiceLogs=1
  - -S
  - ExternalServicesLogVerbosity=4
  - -S
  - BasePathPrefix=/api
  - -S
  - FolderConnectionInterface=0
  - -S
  - Autosave=1
  - -S
  - AutosaveInterval=5
  - -S
  - ValidateJsonWebTokens=2
  - -S
  - JWKSServiceUrl=$(KEYS_URI)/keys/qlik.api.internal
  - -S
  - JWTSignPrivateKeyPath=/etc/secrets/jwtPrivateKey
  - -S
  - JWTSignPrivateKeyId=$(TOKEN_AUTH_PRIVATE_KEY_ID)
  - -S
  - InternalTokenServiceUrl=$(TOKEN_AUTH_URI)/v1
  - -S
  - EnableRenewUserToken=1
  - -S
  - EnableABAC=1
  - -S
  - Gen3=1
  - -S
  - EnableFilePolling=1
  - -S
  - PersistenceMode=2
  - -S
  - EnableAccessControlTrace=1
  - -S
  - SystemRules=/etc/config/rules.yaml
  - -S
  - EnableDataConnectivityService=1
  - -S
  - EnableGrpcFileStreamConnector=1
  - -S
  - DataConnectorServiceUrl=$(DCAAS_URI)
  - -S
  - ConnectivityServiceUrl=$(QIX_DATA_CONNECTION_URI)
  - -S
  - ConnectorGetDataRetryCount=3
  - -S
  - ConnectorGetDataRetryIntervalInSeconds=10
  - -S
  - HostedFileRetryCount=3
  - -S
  - HostedFileRetryIntervalInSeconds=10
  - -S
  - SSEPlugin=GeoOperations,$(GEO_OPERATIONS_URI)
  - -S
  - LicenseServiceUrl=$(LICENSES_URI)
  - -S
  - LicenseCacheTimeoutSeconds=3600
  - -S
  - EnableSpaces=1
  - -S
  - SpacesServiceUrl=$(SPACES_URI)
  - -S
  - EnableEncryptData=1
  - -S
  - UseEncryptionService=1
  - -S
  - EncryptionServiceUrl=$(ENCRYPTION_URI)
  - -S
  - EnableFeatureFlagService=1
  - -S
  - FeatureFlagServiceUrl=$(FEATURE_FLAGS_URI)
  - -S
  - EnableGroupsService=1
  - -S
  - GroupsServiceUrl=$(GROUPS_URI)
  - -S
  - EnableAppExport=1
  - -S
  - EnableTempContentService=1
  - -S
  - TempContentServiceUrl=$(TEMPORARY_CONTENTS_URI)
  - -S
  - UseSTAN=1
  - -S
  - STANUrl=$(NATS_URI)
  - -S
  - STANCluster=$(NATS_STREAMING_CLUSTER_ID)
  - -S
  - STANUseToken=1
  - -S
  - STANMaxReconnect=60
  - -S
  - STANReconnectWait=2
  - -S
  - STANTimeout=10
  - -S
  - UseEventBus=1
  - -S
  - EnvironmentName="example"
  - -S
  - RegionName="example"
  - -S
  - ShutdownWait=1

- op: add
  path: /spec/podSpec/containers/0/env/-
  value:
    name: ACCEPT_EULA
    valueFrom:
      configMapKeyRef:
        key: acceptEULA
        name: engine-configs
- op: add
  path: /spec/podSpec/containers/0/env/-
  value:
    name: KEYS_URI
    valueFrom:
      configMapKeyRef:
        key: keysUri
        name: engine-configs
- op: add
  path: /spec/podSpec/containers/0/env/-
  value:
    name: TOKEN_AUTH_PRIVATE_KEY_ID
    valueFrom:
      secretKeyRef:
        key: tokenAuthPrivateKeyId
        name: engine-secrets
- op: add
  path: /spec/podSpec/containers/0/env/-
  value:
    name: TOKEN_AUTH_URI
    valueFrom:
      configMapKeyRef:
        key: tokenAuthUri
        name: engine-configs
- op: add
  path: /spec/podSpec/containers/0/env/-
  value:
    name: LICENSES_URI
    valueFrom:
      configMapKeyRef:
        key: licensesUri
        name: engine-configs
- op: add
  path: /spec/podSpec/containers/0/env/-
  value:
    name: SPACES_URI
    valueFrom:
      configMapKeyRef:
        key: spacesUri
        name: engine-configs
- op: add
  path: /spec/podSpec/containers/0/env/-
  value:
    name: FEATURE_FLAGS_URI
    valueFrom:
      configMapKeyRef:
        key: featureFlagsUri
        name: engine-configs
- op: add
  path: /spec/podSpec/containers/0/env/-
  value:
    name: GROUPS_URI
    valueFrom:
      configMapKeyRef:
        key: groupsUri
        name: engine-configs
- op: add
  path: /spec/podSpec/containers/0/env/-
  value:
    name: TEMPORARY_CONTENTS_URI
    valueFrom:
      configMapKeyRef:
        key: temporaryContentsUri
        name: engine-configs
- op: add
  path: /spec/podSpec/containers/0/env/-
  value:
    name: NATS_URI
    valueFrom:
      configMapKeyRef:
        key: natsUri
        name: engine-configs
- op: add
  path: /spec/podSpec/containers/0/env/-
  value:
    name: NATS_STREAMING_CLUSTER_ID
    valueFrom:
      configMapKeyRef:
        key: natsStreamingClusterId
        name: engine-configs
- op: add
  path: /spec/podSpec/containers/0/env/-
  value:
    name: ENCRYPTION_URI
    valueFrom:
      configMapKeyRef:
        key: encryptionUri
        name: engine-configs

- op: add
  path: /spec/podSpec/containers/0/env/-
  value:
    name: DCAAS_URI
    valueFrom:
      configMapKeyRef:
        key: dcaasUri
        name: engine-configs
- op: add
  path: /spec/podSpec/containers/0/env/-
  value:
    name: QIX_DATA_CONNECTION_URI
    valueFrom:
      configMapKeyRef:
        key: qixDataConnectionUri
        name: engine-configs
- op: add
  path: /spec/podSpec/containers/0/env/-
  value:
    name: GEO_OPERATIONS_URI
    valueFrom:
      configMapKeyRef:
        key: geoOperationsUri
        name: engine-configs