apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: elastic-infra-generated-operator-secrets
enabled: true
patches:
  - patch: |-
      - op: add
        path: /data
        value:
          tls.crt: (( (ds "data").tls-cert ))
          tls.key: (( (ds "data").tls-key ))
    target:
      kind: Secret
      name: elastic-infra-elastic-infra-tls-secret
