apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: api-keys-component-secrets
enabled: true
patches:
- target:
    kind: SuperSecret
  patch: |-
    apiVersion: qlik.com/v1
    kind: SuperSecret
    metadata:
      name: api-keys-secrets
    stringData:
      tokenAuthPrivateKeyId: (( (ds "data").kid ))
      tokenAuthPrivateKey: |
        ((- "\n"))(( (ds "data").private_key | indent 8 ))
- target:
    kind: Secret
    name: api-keys-secrets
  patch: |-
    - op: add
      path: /stringData
      value:
        mongodbUri: mongodb://$(PREFIX)-mongodb:27017/api-keys?ssl=false
