apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qix-sessions
spec:
  template:
    spec:
      initContainers:
      - name: secret
        image: alpine
        command:
        - sh
        - -c
        - |-
          cat << 'EOF' > /secrets/service-key.yaml
          privateKey: "$(TOKEN_AUTH_PRIVATE_KEY)"
          kid: "$(TOKEN_AUTH_PRIVATE_KEY_ID)"
          authURL: "$(TOKEN_AUTH_URI)/v1/internal-tokens"
          algorithm: "ES384"
          issuer: "qlik.api.internal/qix-sessions"
          subject: "qix-sessions"
          EOF
        env:
        - name: TOKEN_AUTH_URI
          valueFrom:
            configMapKeyRef:
              key: tokenAuthUri
              name: configs
        - name: TOKEN_AUTH_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKey
              name: qix-sessions-secrets
        - name: TOKEN_AUTH_PRIVATE_KEY_ID
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKeyId
              name: qix-sessions-secrets
        volumeMounts:
        - mountPath: /secrets
          name: secrets
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        env:
        - name: SELECTORS_CONFIGMAP_NAME
          value: qix-sessions-configs
        - name: RELOAD_ENGINE_RESOURCE
          value: $(PREFIX)-engine-reload
        - $patch: delete
          name: FEATURE_FLAGS_URI
        - name: FEATURE_FLAGS_URI
          valueFrom:
            configMapKeyRef:
              key: featureFlagsUri
              name: qix-sessions-configs
        - $patch: delete
          name: REDIS_ADDR
        - name: REDIS_URI
          valueFrom:
            configMapKeyRef:
              key: redisUri
              name: qix-sessions-configs
        - name: REDIS_ADDR
          value: $(REDIS_URI):6379
        - $patch: delete
          name: REDIS_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redisPassword
              name: qix-sessions-secrets
        - $patch: delete
          name: $(AUTH_JWKS_URI)
        - name: KEYS_URI
          valueFrom:
            configMapKeyRef:
              key: keysUri
              name: qix-sessions-configs
        - name: AUTH_JWKS_URI
          value: $(KEYS_URI)/keys/qlik.api.internal
        - $patch: delete
          name: PDS_URI
        - name: PDS_URI
          valueFrom:
            configMapKeyRef:
              key: pdsUri
              name: qix-sessions-configs
        - name: NATS_URI
          valueFrom:
            configMapKeyRef:
              key: natsUri
              name: qix-sessions-configs
        - name: NATS_SERVER_ADDRESS
          value: $(NATS_URI)
        - name: NATS_STREAMING_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              key: natsStreamingClusterId
              name: qix-sessions-configs
        - $patch: delete
          name: STAN_CLUSTER_ID
        - name: STAN_CLUSTER_ID
          value: $(NATS_STREAMING_CLUSTER_ID)
        - $patch: delete
          name: APP_SERVICE_URI
        - name: ENGINE_URI
          valueFrom:
            configMapKeyRef:
              key: engineUri
              name: qix-sessions-configs
        - name: APP_SERVICE_URI
          value: $(ENGINE_URI)
        - name: TOKEN_AUTH_URI
          valueFrom:
            configMapKeyRef:
              key: tokenAuthUri
              name: qix-sessions-configs
        - $patch: delete
          name: REGISTER_DYNAMIC_ENGINE
        - name: TOKEN_AUTH_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKey
              name: qix-sessions-secrets
        - name: TOKEN_AUTH_PRIVATE_KEY_ID
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKeyId
              name: qix-sessions-secrets
      serviceAccountName: $(PREFIX)-qix-sessions
      volumes:
      - $patch: delete
        name: qix-sessions-configmap
      - $patch: delete
        name: secrets
      - configMap:
          name: qix-sessions-configs
        name: qix-sessions-configs
      - name: secrets
        emptyDir: {}
