apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: data-connections-component-secrets
enabled: true
patches:
- target:
    kind: SuperSecret
  patch: |-
    apiVersion: qlik.com/v1
    kind: SuperSecret
    metadata:
      name: data-connections-secrets
    stringData:
      tokenAuthPrivateKeyId: (( (ds "data").kid ))
      tokenAuthPrivateKey: |
        ((- "\n"))(( (ds "data").private_key | indent 8 ))
- target:
    kind: Secret
    name: data-connections-secrets
  patch: |-
    - op: add
      path: /stringData
      value:
        mongodbUri: mongodb://$(PREFIX)-mongodb:27017/dcs
