apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: qseokversion
enabled: true
patches:
- target:
    kind: HelmChart
    labelSelector: name!=qliksense-init
  patch: |-
    apiVersion: qlik.com/v1
    kind: HelmChart
    metadata:
      name: helmchart
    releaseNamespace: default
    tmpChartHome: .chartcache/qliksense
    chartRepo: https://qlik.bintray.com/edge
    chartName: qliksense
    chartVersion: 1.37.10

- target:
    kind: HelmChart
    name: qliksense-init
  patch: |-
    apiVersion: qlik.com/v1
    kind: HelmChart
    metadata:
      name: qliksense-init
    releaseNamespace: default
    tmpChartHome: .chartcache/qliksense-init
    chartRepo: https://qlik.bintray.com/edge
    chartName: qliksense-init
    chartVersion: 1.1.0
