apiVersion: qixengine.qlik.com/v1
kind: EngineVariant
metadata:
  labels:
    chart: engine-1.70.2
    heritage: Helm
    release: engine
  name: engine-variant-qliksense
spec:
  args:
    - -S
    - BasePathPrefix=/api
    - -S
    - DocumentDirectory=/qlik/apps
    - -S
    - EnableNumericalAbbreviation=0
    - -S
    - EnableQvwRestImport=1
    - -S
    - EnableRestartOnSessionStall=1
    - -S
    - EnableWebSocketIdleManagement=1
    - -S
    - FolderConnectionInterface=0
    - -S
    - ShutdownWait=1
    - -S
    - AcceptEULA=$(ACCEPT_EULA)
    - -S
    - PrometheusServicePort=9090
    - -S
    - DesktopPort=9076
    - -S
    - AuditLogVerbosity=0
    - -S
    - EnableExtServiceLogs=1
    - -S
    - EventBusLogVerbosity=4
    - -S
    - ExternalServicesLogVerbosity=4
    - -S
    - HttpTrafficLogVerbosity=4
    - -S
    - PerformanceLogVerbosity=0
    - -S
    - QixPerformanceLogVerbosity=0
    - -S
    - SSEVerbosity=4
    - -S
    - ScriptLogVerbosity=4
    - -S
    - SessionLogVerbosity=4
    - -S
    - SmartSearchIndexLogVerbosity=3
    - -S
    - SmartSearchQueryLogVerbosity=3
    - -S
    - SystemLogVerbosity=4
    - -S
    - TrafficLogVerbosity=0
    - -S
    - RestServiceRequestNbrOfRetries=5
    - -S
    - Autosave=1
    - -S
    - AutosaveInterval=5
    - -S
    - JWKSServiceUrl=$(KEYS_URI)/v1/keys/qlik.api.internal
    - -S
    - ValidateJsonWebTokens=2
    - -S
    - EnableRenewUserToken=1
    - -S
    - InternalTokenServiceUrl=$(EDGE_AUTH_URI)/v1
    - -S
    - JWTSignPrivateKeyId=$(TOKEN_AUTH_PRIVATE_KEY_ID)
    - -S
    - JWTSignPrivateKeyPath=/etc/secrets/tokenAuthPrivateKey
    - -S
    - EnableABAC=1
    - -S
    - EnableAccessControlTrace=1
    - -S
    - EnableFilePolling=1
    - -S
    - Gen3=1
    - -S
    - PersistenceMode=2
    - -S
    - SystemRules=/etc/config/rules.yaml
    - -S
    - ConnectivityServiceUrl=$(QIX_DATA_CONNECTION_URI)
    - -S
    - ConnectorGetDataRetryCount=3
    - -S
    - ConnectorGetDataRetryIntervalInSeconds=10
    - -S
    - DataConnectorServiceUrl=$(DCAAS_URI)
    - -S
    - EnableDataConnectivityService=1
    - -S
    - EnableGrpcFileStreamConnector=1
    - -S
    - HostedFileRetryCount=3
    - -S
    - HostedFileRetryIntervalInSeconds=10
    - -S
    - SSEPlugin=GeoOperations,$(PREFIX)-geo-operations:50072
    - -S
    - LicenseCacheTimeoutSeconds=3600
    - -S
    - LicenseServiceUrl=$(LICENSES_URI)
    - -S
    - EnableSpaces=1
    - -S
    - SpacesServiceUrl=$(SPACES_URI)
    - -S
    - EnableEncryptData=1
    - -S
    - EncryptionServiceUrl=$(ENCRYPTION_URI)
    - -S
    - UseEncryptionService=1
    - -S
    - EnableFeatureFlagService=1
    - -S
    - FeatureFlagServiceUrl=$(FEATURE_FLAGS_URI)
    - -S
    - EnableGroupsService=1
    - -S
    - GroupsServiceUrl=$(GROUPS_URI)
    - -S
    - EnableAppExport=1
    - -S
    - EnableDownloadFromTCS=1
    - -S
    - EnableResumableUpload=1
    - -S
    - EnableTempContentService=1
    - -S
    - TempContentServiceUrl=$(TEMPORARY_CONTENTS_URI)
    - -S
    - STANCluster=$(NATS_STREAMING_CLUSTER_ID)
    - -S
    - STANMaxReconnect=60
    - -S
    - STANReconnectWait=2
    - -S
    - STANTimeout=10
    - -S
    - STANUrl=$(NATS_URI)
    - -S
    - STANUseToken=1
    - -S
    - UseEventBus=1
    - -S
    - UseSTAN=1
    - -S
    - UseStatisticsEventProducer=1
    - -S
    - PersistUserState=1
    - -S
    - PersistedUserStateTTLSeconds=1800
    - -S
    - RedisConnectTimeoutMs=100
    - -S
    - RedisHost=$(PREFIX)-engine-redis-user-state
    - -S
    - RedisPort=6379
    - -S
    - RedisSentinelConnectTimeoutMs=100
    - -S
    - RedisSentinelMasterSet=engine-redis-user-state
    - -S
    - RedisSentinelPort=26379
    - -S
    - RedisSentinelRetryIntervalMs=100
    - -S
    - RedisSentinelSocketTimeoutMs=100
    - -S
    - RedisSocketTimeoutMs=100
    - -S
    - UseRedis=1
    - -S
    - UseRedisSentinel=1
    - -S
    - EnvironmentName="example"
    - -S
    - RegionName="example"
    - -S
    - SessionTimeoutSec=1200
  engineTemplateName: engine-template-default
  env:
    - name: ACCEPT_EULA
      valueFrom:
        configMapKeyRef:
          key: acceptEULA
          name: engine-configs
    - name: KEYS_URI
      valueFrom:
        configMapKeyRef:
          key: keysUri
          name: engine-configs
    - name: TOKEN_AUTH_PRIVATE_KEY_ID
      valueFrom:
        secretKeyRef:
          key: tokenAuthPrivateKeyId
          name: engine-secrets
    - name: EDGE_AUTH_URI
      valueFrom:
        configMapKeyRef:
          key: edgeAuthUri
          name: engine-configs
    - name: LICENSES_URI
      valueFrom:
        configMapKeyRef:
          key: licensesUri
          name: engine-configs
    - name: SPACES_URI
      valueFrom:
        configMapKeyRef:
          key: spacesUri
          name: engine-configs
    - name: FEATURE_FLAGS_URI
      valueFrom:
        configMapKeyRef:
          key: featureFlagsUri
          name: engine-configs
    - name: GROUPS_URI
      valueFrom:
        configMapKeyRef:
          key: groupsUri
          name: engine-configs
    - name: TEMPORARY_CONTENTS_URI
      valueFrom:
        configMapKeyRef:
          key: temporaryContentsUri
          name: engine-configs
    - name: NATS_URI
      valueFrom:
        configMapKeyRef:
          key: natsUri
          name: engine-configs
    - name: NATS_STREAMING_CLUSTER_ID
      valueFrom:
        configMapKeyRef:
          key: natsStreamingClusterId
          name: engine-configs
    - name: ENCRYPTION_URI
      valueFrom:
        configMapKeyRef:
          key: encryptionUri
          name: engine-configs
    - name: DCAAS_URI
      valueFrom:
        configMapKeyRef:
          key: dcaasUri
          name: engine-configs
  image: qlik-docker-qsefe.bintray.io/engine:12.710.0
  labels:
    qlik.com/engine-type: qliksense
---
apiVersion: qixengine.qlik.com/v1
kind: EngineVariant
metadata:
  labels:
    chart: engine-1.70.2
    heritage: Helm
    release: engine
  name: engine-variant-qlikview
spec:
  annotations:
    prometheus.io/job: engine-qlikview
  args:
    - -S
    - BasePathPrefix=/api
    - -S
    - DocumentDirectory=/qlik/apps
    - -S
    - EnableNumericalAbbreviation=0
    - -S
    - EnableQvwRestImport=1
    - -S
    - EnableRestartOnSessionStall=1
    - -S
    - EnableWebSocketIdleManagement=1
    - -S
    - FolderConnectionInterface=0
    - -S
    - ShutdownWait=1
    - -S
    - AcceptEULA=$(ACCEPT_EULA)
    - -S
    - PrometheusServicePort=9090
    - -S
    - DesktopPort=9076
    - -S
    - AuditLogVerbosity=0
    - -S
    - EnableExtServiceLogs=1
    - -S
    - EventBusLogVerbosity=4
    - -S
    - ExternalServicesLogVerbosity=4
    - -S
    - HttpTrafficLogVerbosity=4
    - -S
    - PerformanceLogVerbosity=0
    - -S
    - QixPerformanceLogVerbosity=0
    - -S
    - SSEVerbosity=4
    - -S
    - ScriptLogVerbosity=4
    - -S
    - SessionLogVerbosity=4
    - -S
    - SmartSearchIndexLogVerbosity=3
    - -S
    - SmartSearchQueryLogVerbosity=3
    - -S
    - SystemLogVerbosity=4
    - -S
    - TrafficLogVerbosity=0
    - -S
    - RestServiceRequestNbrOfRetries=5
    - -S
    - Autosave=1
    - -S
    - AutosaveInterval=5
    - -S
    - JWKSServiceUrl=$(KEYS_URI)/v1/keys/qlik.api.internal
    - -S
    - ValidateJsonWebTokens=2
    - -S
    - EnableRenewUserToken=1
    - -S
    - InternalTokenServiceUrl=$(EDGE_AUTH_URI)/v1
    - -S
    - JWTSignPrivateKeyId=$(TOKEN_AUTH_PRIVATE_KEY_ID)
    - -S
    - JWTSignPrivateKeyPath=/etc/secrets/tokenAuthPrivateKey
    - -S
    - EnableABAC=1
    - -S
    - EnableAccessControlTrace=1
    - -S
    - EnableFilePolling=1
    - -S
    - Gen3=1
    - -S
    - PersistenceMode=2
    - -S
    - SystemRules=/etc/config/rules.yaml
    - -S
    - ConnectivityServiceUrl=$(QIX_DATA_CONNECTION_URI)
    - -S
    - ConnectorGetDataRetryCount=3
    - -S
    - ConnectorGetDataRetryIntervalInSeconds=10
    - -S
    - DataConnectorServiceUrl=$(DCAAS_URI)
    - -S
    - EnableDataConnectivityService=1
    - -S
    - EnableGrpcFileStreamConnector=1
    - -S
    - HostedFileRetryCount=3
    - -S
    - HostedFileRetryIntervalInSeconds=10
    - -S
    - SSEPlugin=GeoOperations,$(PREFIX)-geo-operations:50072
    - -S
    - LicenseCacheTimeoutSeconds=3600
    - -S
    - LicenseServiceUrl=$(LICENSES_URI)
    - -S
    - EnableSpaces=1
    - -S
    - SpacesServiceUrl=$(SPACES_URI)
    - -S
    - EnableEncryptData=1
    - -S
    - EncryptionServiceUrl=$(ENCRYPTION_URI)
    - -S
    - UseEncryptionService=1
    - -S
    - EnableFeatureFlagService=1
    - -S
    - FeatureFlagServiceUrl=$(FEATURE_FLAGS_URI)
    - -S
    - EnableGroupsService=1
    - -S
    - GroupsServiceUrl=$(GROUPS_URI)
    - -S
    - EnableAppExport=1
    - -S
    - EnableDownloadFromTCS=1
    - -S
    - EnableResumableUpload=1
    - -S
    - EnableTempContentService=1
    - -S
    - TempContentServiceUrl=$(TEMPORARY_CONTENTS_URI)
    - -S
    - STANCluster=$(NATS_STREAMING_CLUSTER_ID)
    - -S
    - STANMaxReconnect=60
    - -S
    - STANReconnectWait=2
    - -S
    - STANTimeout=10
    - -S
    - STANUrl=$(NATS_URI)
    - -S
    - STANUseToken=1
    - -S
    - UseEventBus=1
    - -S
    - UseSTAN=1
    - -S
    - UseStatisticsEventProducer=1
    - -S
    - PersistUserState=1
    - -S
    - PersistedUserStateTTLSeconds=1800
    - -S
    - RedisConnectTimeoutMs=100
    - -S
    - RedisHost=$(PREFIX)-engine-redis-user-state
    - -S
    - RedisPort=6379
    - -S
    - RedisSentinelConnectTimeoutMs=100
    - -S
    - RedisSentinelMasterSet=engine-redis-user-state
    - -S
    - RedisSentinelPort=26379
    - -S
    - RedisSentinelRetryIntervalMs=100
    - -S
    - RedisSentinelSocketTimeoutMs=100
    - -S
    - RedisSocketTimeoutMs=100
    - -S
    - UseRedis=1
    - -S
    - UseRedisSentinel=1
    - -S
    - EnvironmentName="example"
    - -S
    - RegionName="example"
    - -S
    - SessionTimeoutSec=1200
    - -S
    - BasicQlikviewEnabled=1
    - -S
    - BundledContentsRootFolder=/usr/local/share/Bundled
    - -S
    - SkiaFontPaths=/usr/share/fonts
  engineTemplateName: engine-template-default
  env:
    - name: ACCEPT_EULA
      valueFrom:
        configMapKeyRef:
          key: acceptEULA
          name: engine-configs
    - name: KEYS_URI
      valueFrom:
        configMapKeyRef:
          key: keysUri
          name: engine-configs
    - name: TOKEN_AUTH_PRIVATE_KEY_ID
      valueFrom:
        secretKeyRef:
          key: tokenAuthPrivateKeyId
          name: engine-secrets
    - name: EDGE_AUTH_URI
      valueFrom:
        configMapKeyRef:
          key: edgeAuthUri
          name: engine-configs
    - name: LICENSES_URI
      valueFrom:
        configMapKeyRef:
          key: licensesUri
          name: engine-configs
    - name: SPACES_URI
      valueFrom:
        configMapKeyRef:
          key: spacesUri
          name: engine-configs
    - name: FEATURE_FLAGS_URI
      valueFrom:
        configMapKeyRef:
          key: featureFlagsUri
          name: engine-configs
    - name: GROUPS_URI
      valueFrom:
        configMapKeyRef:
          key: groupsUri
          name: engine-configs
    - name: TEMPORARY_CONTENTS_URI
      valueFrom:
        configMapKeyRef:
          key: temporaryContentsUri
          name: engine-configs
    - name: NATS_URI
      valueFrom:
        configMapKeyRef:
          key: natsUri
          name: engine-configs
    - name: NATS_STREAMING_CLUSTER_ID
      valueFrom:
        configMapKeyRef:
          key: natsStreamingClusterId
          name: engine-configs
    - name: ENCRYPTION_URI
      valueFrom:
        configMapKeyRef:
          key: encryptionUri
          name: engine-configs
    - name: DCAAS_URI
      valueFrom:
        configMapKeyRef:
          key: dcaasUri
          name: engine-configs
  image: qlik-docker-qsefe.bintray.io/engine-qv:12.710.0
  labels:
    qlik.com/engine-type: qlikview
---
apiVersion: qixengine.qlik.com/v1
kind: EngineVariant
metadata:
  labels:
    chart: engine-1.70.2
    heritage: Helm
    release: engine
  name: sense-reload-engine-variant
spec:
  annotations:
    prometheus.io/job: engine-reload
  args:
    - -S
    - BasePathPrefix=/api
    - -S
    - DocumentDirectory=/qlik/apps
    - -S
    - EnableNumericalAbbreviation=0
    - -S
    - EnableQvwRestImport=1
    - -S
    - EnableRestartOnSessionStall=1
    - -S
    - EnableWebSocketIdleManagement=1
    - -S
    - FolderConnectionInterface=0
    - -S
    - ShutdownWait=1
    - -S
    - AcceptEULA=$(ACCEPT_EULA)
    - -S
    - PrometheusServicePort=9090
    - -S
    - DesktopPort=9076
    - -S
    - AuditLogVerbosity=0
    - -S
    - EnableExtServiceLogs=1
    - -S
    - EventBusLogVerbosity=4
    - -S
    - ExternalServicesLogVerbosity=4
    - -S
    - HttpTrafficLogVerbosity=4
    - -S
    - PerformanceLogVerbosity=0
    - -S
    - QixPerformanceLogVerbosity=0
    - -S
    - SSEVerbosity=4
    - -S
    - ScriptLogVerbosity=4
    - -S
    - SessionLogVerbosity=4
    - -S
    - SmartSearchIndexLogVerbosity=3
    - -S
    - SmartSearchQueryLogVerbosity=3
    - -S
    - SystemLogVerbosity=4
    - -S
    - TrafficLogVerbosity=0
    - -S
    - RestServiceRequestNbrOfRetries=5
    - -S
    - Autosave=1
    - -S
    - AutosaveInterval=5
    - -S
    - JWKSServiceUrl=$(KEYS_URI)/v1/keys/qlik.api.internal
    - -S
    - ValidateJsonWebTokens=2
    - -S
    - EnableRenewUserToken=1
    - -S
    - InternalTokenServiceUrl=$(EDGE_AUTH_URI)/v1
    - -S
    - JWTSignPrivateKeyId=$(TOKEN_AUTH_PRIVATE_KEY_ID)
    - -S
    - JWTSignPrivateKeyPath=/etc/secrets/tokenAuthPrivateKey
    - -S
    - EnableABAC=1
    - -S
    - EnableAccessControlTrace=1
    - -S
    - EnableFilePolling=1
    - -S
    - Gen3=1
    - -S
    - PersistenceMode=2
    - -S
    - SystemRules=/etc/config/rules.yaml
    - -S
    - ConnectivityServiceUrl=$(QIX_DATA_CONNECTION_URI)
    - -S
    - ConnectorGetDataRetryCount=3
    - -S
    - ConnectorGetDataRetryIntervalInSeconds=10
    - -S
    - DataConnectorServiceUrl=$(DCAAS_URI)
    - -S
    - EnableDataConnectivityService=1
    - -S
    - EnableGrpcFileStreamConnector=1
    - -S
    - HostedFileRetryCount=3
    - -S
    - HostedFileRetryIntervalInSeconds=10
    - -S
    - SSEPlugin=GeoOperations,$(PREFIX)-geo-operations:50072
    - -S
    - LicenseCacheTimeoutSeconds=3600
    - -S
    - LicenseServiceUrl=$(LICENSES_URI)
    - -S
    - EnableSpaces=1
    - -S
    - SpacesServiceUrl=$(SPACES_URI)
    - -S
    - EnableEncryptData=1
    - -S
    - EncryptionServiceUrl=$(ENCRYPTION_URI)
    - -S
    - UseEncryptionService=1
    - -S
    - EnableFeatureFlagService=1
    - -S
    - FeatureFlagServiceUrl=$(FEATURE_FLAGS_URI)
    - -S
    - EnableGroupsService=1
    - -S
    - GroupsServiceUrl=$(GROUPS_URI)
    - -S
    - EnableAppExport=1
    - -S
    - EnableDownloadFromTCS=1
    - -S
    - EnableResumableUpload=1
    - -S
    - EnableTempContentService=1
    - -S
    - TempContentServiceUrl=$(TEMPORARY_CONTENTS_URI)
    - -S
    - STANCluster=$(NATS_STREAMING_CLUSTER_ID)
    - -S
    - STANMaxReconnect=60
    - -S
    - STANReconnectWait=2
    - -S
    - STANTimeout=10
    - -S
    - STANUrl=$(NATS_URI)
    - -S
    - STANUseToken=1
    - -S
    - UseEventBus=1
    - -S
    - UseSTAN=1
    - -S
    - UseStatisticsEventProducer=1
    - -S
    - PersistUserState=1
    - -S
    - PersistedUserStateTTLSeconds=1800
    - -S
    - RedisConnectTimeoutMs=100
    - -S
    - RedisHost=$(PREFIX)-engine-redis-user-state
    - -S
    - RedisPort=6379
    - -S
    - RedisSentinelConnectTimeoutMs=100
    - -S
    - RedisSentinelMasterSet=engine-redis-user-state
    - -S
    - RedisSentinelPort=26379
    - -S
    - RedisSentinelRetryIntervalMs=100
    - -S
    - RedisSentinelSocketTimeoutMs=100
    - -S
    - RedisSocketTimeoutMs=100
    - -S
    - UseRedis=1
    - -S
    - UseRedisSentinel=1
    - -S
    - EnvironmentName="example"
    - -S
    - RegionName="example"
    - -S
    - SessionTimeoutSec=1200
  engineTemplateName: engine-template-default
  env:
    - name: ACCEPT_EULA
      valueFrom:
        configMapKeyRef:
          key: acceptEULA
          name: engine-configs
    - name: KEYS_URI
      valueFrom:
        configMapKeyRef:
          key: keysUri
          name: engine-configs
    - name: TOKEN_AUTH_PRIVATE_KEY_ID
      valueFrom:
        secretKeyRef:
          key: tokenAuthPrivateKeyId
          name: engine-secrets
    - name: EDGE_AUTH_URI
      valueFrom:
        configMapKeyRef:
          key: edgeAuthUri
          name: engine-configs
    - name: LICENSES_URI
      valueFrom:
        configMapKeyRef:
          key: licensesUri
          name: engine-configs
    - name: SPACES_URI
      valueFrom:
        configMapKeyRef:
          key: spacesUri
          name: engine-configs
    - name: FEATURE_FLAGS_URI
      valueFrom:
        configMapKeyRef:
          key: featureFlagsUri
          name: engine-configs
    - name: GROUPS_URI
      valueFrom:
        configMapKeyRef:
          key: groupsUri
          name: engine-configs
    - name: TEMPORARY_CONTENTS_URI
      valueFrom:
        configMapKeyRef:
          key: temporaryContentsUri
          name: engine-configs
    - name: NATS_URI
      valueFrom:
        configMapKeyRef:
          key: natsUri
          name: engine-configs
    - name: NATS_STREAMING_CLUSTER_ID
      valueFrom:
        configMapKeyRef:
          key: natsStreamingClusterId
          name: engine-configs
    - name: ENCRYPTION_URI
      valueFrom:
        configMapKeyRef:
          key: encryptionUri
          name: engine-configs
    - name: DCAAS_URI
      valueFrom:
        configMapKeyRef:
          key: dcaasUri
          name: engine-configs
  image: qlik-docker-qsefe.bintray.io/engine:12.710.0
  labels:
    qlik.com/engine-type: qliksense
---
