apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: tenants
resources:
  - ../../../transformers
transformers:
- ../../../../../.operator/transformers
- ../../../../../configuration/transformers
#Disable all transformers except these
patches:
- target:
    labelSelector: >-
      key notin (
        ingressClass,
        ingressAuthUrl,
        featureFlagsUri,
        natsStreamingClusterId,
        natsUri,
        keysUri,
        mongoDbUri,
        usersUri,
        licensesUri,
        tokenAuthUri,
        tokenAuthPrivateKey,
        tokenAuthPrivateKeyId
        )
  patch: |-
    - op: replace
      path: /enabled
      value: false
    - op: replace
      path: /default
      value: true
